name: Continuous Integration

on:
    push:
        branches:
            - main
    workflow_call:
    workflow_dispatch:
    pull_request:
        types: [synchronize]

jobs:
    ci:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install, build, and upload
              uses: withastro/action@v1

            - name: Formatting
              run: npm run format:check

            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v1
